name: Deploy Documentation to GitHub Pages (DISABLED)

on:
  # Disable this workflow
  workflow_dispatch:
    branches: []
  # push:
  #   branches:
  #     - main
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Install Jekyll
        run: |
          cd docs
          gem install jekyll bundler
          bundle init
          echo 'gem "jekyll"' >> Gemfile
          echo 'gem "jekyll-theme-minimal"' >> Gemfile
          echo 'gem "jekyll-sitemap"' >> Gemfile
          echo 'gem "jekyll-seo-tag"' >> Gemfile
          bundle install
          
      - name: Build with Jekyll
        run: |
          cd docs
          bundle exec jekyll build --destination ../_site
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 