/**
 * Export all stores
 * This file is auto-generated by the build process
 */

// This is a placeholder - the actual exports will be generated
// by scanning the stores directory during build

// Example export format:
// export { useAuthStore } from './auth'
// export { useUserStore } from './user' 