
module.exports = (To, { url, appName, appAuthor }) => ({
	To,
	Subject: `${appName} - Email Verification`,
	Text: `
Hey there,

Here's your verification email for ${appName}. Please follow the link to complete your email verification:

${url}

Thanks!
${appAuthor}

-------

If you're having trouble with the link above, copy and paste the URL into your web browser. Also, this email was auto-generated by your email being registered with our system. If this was in error, please email us back and we'll look into what's going on.

`
})


